---
- name: Add Java Oracle repository into source list
  apt_repository: repo='ppa:webupd8team/java' update_cache=yes

- name: Accept License
  debconf: 
    name='oracle-java8-installer'
    question='shared/accepted-oracle-license-v1-1'
    value='true'
    vtype='select'

- name: Install oracle java
  apt: name=oracle-java8-installer state=latest
  
- name: Install additional packages
  apt: name={{ item }}
  with_items:
    - maven
    - ant

# JENKINS REPOSITORY KEY
- name: Add jenkins repository key
  apt_key: 
    url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key
    state=present





