---
- name: Update apt
  apt: update_cache=yes

- name: Install Java OpenJDK
  apt: name={{ item }} state=latest force=yes
  with_items:
    - openjdk-7-jdk
    - ant

- name: Configure JAVA_HOME env
  lineinfile: dest="/etc/environment" line="JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/"

- name: Add apt repository key
  apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key

- name: Add repository to sources
  lineinfile: dest="/etc/apt/sources.list.d/jenkins.list" line="deb http://pkg.jenkins-ci.org/debian binary/" state=present create=yes

- name: Install jenkins
  apt: name=jenkins state=latest force=yes update_cache=yes

- name: Create nginx configuration
  template:
    src: vhost-configuration.js2
    dest: /etc/nginx/sites-available/jenkins-{{ parameters.project_name }}-configuration.conf
#
- name: Enable nginx vhosts
  file:
    src: /etc/nginx/sites-available/jenkins-{{ parameters.project_name }}-configuration.conf
    dest: /etc/nginx/sites-enabled/jenkins-{{ parameters.project_name }}-configuration.conf
    state: link
  notify: restart nginx

- name: Waiting for jenkins running
  wait_for: path=/etc/init.d/jenkins state=started delay=60

- name: Download jenkins cli
  get_url: url=http://localhost:8080/jnlpJars/jenkins-cli.jar dest=/usr/share/jenkins/jenkins-cli.jar mode=0777

- name: Update plugins list
  shell: "curl  -L http://updates.jenkins-ci.org/update-center.json | sed '1d;$d' | curl -X POST -H 'Accept: application/json' -d @- http://localhost:8080/updateCenter/byId/default/postBack"

- name: Install jenkins's plugins required for above libs
  shell: java -jar /usr/share/jenkins/jenkins-cli.jar -s http://localhost:8080 install-plugin {{ item }}
  with_items: jenkins_plugins
  notify: restart jenkins