--- 
- name: Update apt
  apt: update_cache=yes

- name: Install common tools
  apt: name={{ item }} state=latest
  with_items:
    - git-core
    - vim
    - curl
    - mc
    - acl
    - git
    - subversion
    - git-svn
    - libxml2-utils
    - graphviz
    - imagemagick
    - libmagickwand-dev
    - maven
    - ant
